name: repay
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  feather_icons_flutter: ^4.7.4
  http: ^0.12.1
  ng_fontawesome: ^5.12.1
  font_awesome: ^5.10.1
  font_awesome_flutter: ^8.8.1
  cupertino_icons: ^0.1.3
  country_code_picker: ^1.3.15
  simple_animations: ^2.2.1
  hive: ^1.4.1+1
  toast: ^0.1.5
  path_provider: ^1.6.10
  flutter_launcher_icons: ^0.7.5
  hive_flutter: ^0.3.0+2
  google_fonts: ^1.1.0
  percent_indicator: ^2.1.4
  shared_preferences: ^0.5.7+3
  dots_indicator: ^1.1.0
  sleek_circular_slider: ^1.1.0
  streaming_shared_preferences: ^1.0.1
  workmanager: ^0.2.2
  flutter_local_notifications: ^1.4.4+1
  qr_code_scanner: ^0.0.13
  fab_circular_menu: ^1.0.0













dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/repay_logo.png"  


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/repay_logo.png
   - assets/images/buy.png
   - assets/images/analytics.png
   - assets/images/save.jpg
   - assets/images/no_data.png
   - assets/images/ks.png
   - assets/images/keep.png
   - assets/icons/merchant.png
   - assets/icons/money_received.png
   - assets/icons/money_sent.png
   - assets/images/not_found.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
